config/routes.rb
Lulusum::Application.routes.draw do
  resources :matches

  resources :tickets

  resources :concerts
  
  devise_for :users, :controllers => { :registrations => "registrations" }

  

  resources :users do
    member do
      get :set_admin, :unset_admin
    end
    
    collection do
      get :love
    end
    
  end
  
  get "main_pages/home"
  get "main_pages/about"
  get "main_pages/help"
  get "main_pages/terms"

  
  root :to => "main_pages#home"
  
  match '/users/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  
  
  match '/help', to: 'main_pages#help'
  match '/about', to: 'main_pages#about'
  match '/terms', to: 'main_pages#terms'
  

  resources :test_models

end

app/views/shared/_side.html.erb
<div class='row-fluid'>
	<div class='span5'>
		<center>
			<img src='<%= current_user.image_url%>' width='50'/>
		
			<h4> <%= current_user.name %></h4>
		</center>	
	</div>
	<div class='span5'>
		<center>
		<img src='<%= current_user.avatar_image_url%>' width='50'>
		
			<h4><%= current_user.tribe%></h4>
		</center>	
	</div>	
	
</div>


<div class="sidebar-nav">



	<ul class="nav nav-list">
		<li class="nav-header">공연리스트</li>
		<li><%= link_to "진행중인 공연", concerts_path  %></li>
		<li><%= link_to "전체 공연", concerts_path(:filter=>'all')  %></li>
		<li><%= link_to "준비중인 공연", concerts_path(:filter=>'ready')  %></li>
		<li><%= link_to "지나간 공연", concerts_path(:filter=>'finished')  %></li>
		
		<li class="nav-header">신청리스트</li>
		<li><%= link_to "내 신청리스트", tickets_path  %></li>
		<!-- ><li>
			<%= link_to "찜 공연", concerts_path(:filter=>'favorit')  %>
		</li> -->
		<li>
			<%= link_to "지난 신청리스트", tickets_path(:matched=>'true')  %>
		</li>
		<!--
		<li>
			<%= link_to "관심친구", love_users_path  %>
		</li> -->
		
		<% if current_user.admin?%>
		<li class="nav-header">관리자</li>
		<li><%= link_to "공연생성", new_concert_path  %></li>
		<li><%= link_to "매칭하기", new_match_path  %></li>
		<li><%= link_to "전체사용자", users_path  %></li>
		<li><%= link_to "전체신청", tickets_path(:all=>'true')  %></li>
		<%end%>

	</ul>
</div><!--/.well -->