config/routes.rb
Lulusum::Application.routes.draw do
  resources :matches

  resources :tickets

  resources :concerts
  
  devise_for :users, :controllers => { :registrations => "registrations" }

  

  resources :users do
    member do
      get :set_admin, :unset_admin
    end
    
    collection do
      get :love
    end
    
  end
  
  get "main_pages/home"
  get "main_pages/about"
  get "main_pages/help"
  get "main_pages/terms"

  
  root :to => "main_pages#home"
  
  match '/users/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  
  
  match '/help', to: 'main_pages#help'
  match '/about', to: 'main_pages#about'
  match '/terms', to: 'main_pages#terms'
  

  resources :test_models

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  attr_accessible :available, :breakday, :category, :description, :enddate, :poster, :price, :reflink, :score, :startdate, :status, :title
  attr_accessible :location, :schedules_attributes  
  
  has_many :relationship_favorit_concerts, :dependent => :destroy
  has_many :favorit_users, :through=> :relationship_favorit_concerts, :source => :user
  
  has_many :tickets
  has_many :schedules
  accepts_nested_attributes_for :schedules, allow_destroy: true
  
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_filter, except: [:index]
  # GET /concerts
  # GET /concerts.json
  def index
    if params[:filter] == 'all'
    @concerts = Concert.all
    elsif params[:filter] == 'finished'
      @concerts = Concert.where(:status => 'finished')
    elsif params[:filter] == 'ready'
      @concerts = Concert.where(:status => 'ready')
    else
      @concerts = Concert.where(:status => 'active')
    end
      
      

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concerts }
    end
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
    @concert = Concert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concert }
    end
  end

  # GET /concerts/new
  # GET /concerts/new.json
  def new
    @concert = Concert.new
    
    1.times { @concert.schedules.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concert }
    end
  end

  # GET /concerts/1/edit
  def edit
    @concert = Concert.find(params[:id])
    
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(params[:concert])

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render json: @concert, status: :created, location: @concert }
      else
        format.html { render action: "new" }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /concerts/1
  # PUT /concerts/1.json
  def update
    @concert = Concert.find(params[:id])

    respond_to do |format|
      if @concert.update_attributes(params[:concert])
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert = Concert.find(params[:id])
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to concerts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>
      <ul>
      <% @concert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= f.label :title, "제목"%>
    <%= f.text_field :title %>
    
    <%= f.label :title, "시작일"%>
    <%= f.date_select :startdate %>
    <%= f.label :title, "끝나는날"%>
    <%= f.date_select :enddate %>
    
    <%= f.label :poster, "포스터링크"%>
    <%= f.text_field :poster %>
   	
   	<%= f.label :description, "설명"%>
    <%= f.text_field :description %>
    
    <%= f.label :status, "상태"%>
    <%= f.select :status, options_for_select([['ready', 'ready'], ['active', 'active'], ['finished', 'finished']], @concert.status) %>
    
    <%= f.label :price, "가격"%>
    <%= f.text_field :price %>
    
    <%= f.label :location, "위치"%>
	<%= f.text_field :location %>
	<%= f.label :available, "가능티켓"%>
    <%= f.text_field :available %>
  </div>

					 
	<%= f.fields_for :schedules do |builder| %>
   	  <%= render 'schedule_fields', f: builder %>
  	<% end %>
	<%= link_to_add_fields "Add Schedule", f, :schedules %>
	

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/concerts/_schedule_fields.html.erb
<fieldset> 
  <%= f.label :start_time, "스케쥴" %>
  <%= f.datetime_select :start_time %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/concerts/edit.html.erb
<h1>공연 수정하기</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<% if params[:filter] == 'favorit'%>
<h4>찜한 공연 리스트</h4>
<%else%>
<h4>공연 리스트</h4>
<%end%>
<div class="row-fluid">
	<div class="span12">
			<div class="row-fluid">
            
            	<% @concerts.each_with_index do |concert, index| %>
            	<%if index%3==0 %> <ul class="thumbnails"> <%end%>
              <li class="span4">
                <div class="thumbnail">
                 <img src='<%= concert.poster%>'>
                 	<div class="caption">
                 		<h4><%= link_to concert.title, new_ticket_path(:concert_id=>concert.id) =%>
                 			<%if current_user.admin?%> <small><%= link_to '수정', edit_concert_path(concert) %>|<%= link_to '삭제', concert, confirm: 'Are you sure?', method: :delete %></small><%end%>
                 		</h4>
                 		<%= concert.description %>
                    </div>
                </div>
              </li>
              <%if index%3==2%> </ul> <%end%> 
             <%end%>
             
              </div>
	</div>

</div>



<br />

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>공연생성하기</h1>

<%= render 'form' %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @concert.title %>
</p>

<p>
  <b>Startdate:</b>
  <%= @concert.startdate %>
</p>

<p>
  <b>Enddate:</b>
  <%= @concert.enddate %>
</p>

<ul>
<% @concert.schedules.each do |schedule| %>
  <li>
    	<%= schedule.start_time%>   
  </li>
<% end %>
 </ul>
<p>
  <b>Poster:</b>
  <%= @concert.poster %>
</p>

<p>
  <b>Reflink:</b>
  <%= @concert.reflink %>
</p>

<p>
  <b>Description:</b>
  <%= @concert.description %>
</p>

<p>
  <b>Status:</b>
  <%= @concert.status %>
</p>

<p>
  <b>Category:</b>
  <%= @concert.category %>
</p>

<p>
  <b>Score:</b>
  <%= @concert.score %>
</p>

<p>
  <b>Breakday:</b>
  <%= @concert.breakday %>
</p>

<p>
  <b>Price:</b>
  <%= @concert.price %>
</p>

<p>
  <b>Available:</b>
  <%= @concert.available %>
</p>


<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>