config/routes.rb
Lulusum::Application.routes.draw do
  resources :matches

  resources :tickets

  resources :concerts
  
  devise_for :users, :controllers => { :registrations => "registrations" }

  

  resources :users do
    member do
      get :set_admin, :unset_admin
    end
    
    collection do
      get :love
    end
    
  end
  
  get "main_pages/home"
  get "main_pages/about"
  get "main_pages/help"
  get "main_pages/terms"

  
  root :to => "main_pages#home"
  
  match '/users/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  
  
  match '/help', to: 'main_pages#help'
  match '/about', to: 'main_pages#about'
  match '/terms', to: 'main_pages#terms'
  

  resources :test_models

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :concert_id, :schedule_id, :status
  
  belongs_to :concert
  belongs_to :schedule
  has_many :tickets
end

app/controllers/matches_controller.rb
# coding : utf-8

class MatchesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_filter, except: [:show]
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])
    
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new
    
    @boy_tickets = Ticket.joins(:user).where('users.gender' => '남자', :status => nil)
    @girl_tickets = Ticket.joins(:user).where('users.gender' => '여자', :status => nil)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
    @boy_tickets = Ticket.joins(:user).where('users.gender' => '남자', :status => nil)
    @girl_tickets = Ticket.joins(:user).where('users.gender' => '여자', :status => nil)
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])
    @ticket_ids = params[:ticket_ids]

    respond_to do |format|
      if @match.save
        
        @ticket_ids.each do |t_id|
          ticket = Ticket.find(t_id)
          ticket.match = @match
          ticket.status = 'matched' 
          ticket.save
        end 
        
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])
    @ticket_ids = params[:ticket_ids]
     
     
    @match.tickets.each do |tticket|
          tticket.match_id = nil
          tticket.status = nil 
          tticket.save
    end 

    respond_to do |format|
      if @match.update_attributes(params[:match])
        
        @ticket_ids.each do |t_id|
          ticket = Ticket.find(t_id)
          ticket.match = @match
          ticket.status = 'matched' 
          ticket.save
        end 
        
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= simple_form_for(@match) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :concert_id, :collection=>Concert.all, :label_method=>'title' %>
    <%= f.input :schedule_id, :collection=>Schedule.all, :label_method=>'label_full' %>
  </div>

<div class='row-fluid'>
	<div class="span12">
		<h4>여성회원</h4>
		<table class="table">
		<% @girl_tickets.each do |ticket|%>
			<tr>
				<td><input type="checkbox" name="ticket_ids[]" value='<%=ticket.id%>' /></td>
				<td><%= ticket.concert.title%></td>
				<td><%= ticket.user.name%></td>
				<td><ul><% ticket.select_schedules.each do |schedule| %>
					<li><%= schedule.label_start_time%></li>
					<% end %>
					</ul>
				</td>
				<td><ul>
					<li><%= ticket.filter_type_1%></li>
					<li><%= ticket.filter_type_2%></li>
					<li><%= ticket.filter_type_3%></li>
					</td>
				<td><ul>
					<li>연령:<%= ticket.filter_age%></li>
					<li>직업:<%= ticket.filter_job%></li>
					<li>종족:<%= ticket.filter_tribe%></li>
					</td>
				
			</tr>
		<%end%>
		</table>
		
		<h4>남성회원</h4>
		<table class="table">
		<% @boy_tickets.each do |ticket|%>
			<tr>
				<td><input type="checkbox" name="ticket_ids[]" value='<%=ticket.id%>' /></td>
				<td><%= ticket.concert.title%></td>
				<td><%= ticket.user.name%></td>
				<td><ul><% ticket.select_schedules.each do |schedule| %>
					<li><%= schedule.label_start_time%></li>
					<% end %>
					</ul>
				</td>
				<td><ul>
					<li><%= ticket.filter_type_1%></li>
					<li><%= ticket.filter_type_2%></li>
					<li><%= ticket.filter_type_3%></li>
					</td>
				<td><ul>
					<li>연령:<%= ticket.filter_age%></li>
					<li>직업:<%= ticket.filter_job%></li>
					<li>종족:<%= ticket.filter_tribe%></li>
					</td>
				
			</tr>
		<%end%>
		</table>
		
	</div>
</div>	
  
  
  
    <%= f.button :submit, "매칭하기" %>
  
<% end %>

app/views/matches/edit.html.erb
<h1>매칭수정</h1>

<b> 현재참석자 </b>
<% @match.tickets.each do |ticket|%>
	<li style="padding-bottom: 5px;"><img src='<%= ticket.user.image_url%>' width='30px'> <%=ticket.user.name %> (<%=ticket.user.gender %>)</li>
	<%end%>
<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h4>함께한 공연</h4>

<table class="table">
  <tr>
    <th>Concert</th>
    <th>Status</th>
    <th>Schedule</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.concert_id %></td>
    <td><%= match.status %></td>
    <td><%= match.schedule %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>사랑의 짝찟기</h1>

<%= render 'form' %>


<br>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>공연제목 : </b>
  <%= Concert.find(@match.concert_id).title %>
</p>

<p>
  <b>일시 : </b>
  <%= Schedule.find(@match.schedule_id).label_full %>
</p>

<b>참석자 : </b>
<ul>
	<%if @match.tickets %>
	<% @match.tickets.each do |ticket|%>
	<li style="padding-bottom: 5px;"><img src='<%= ticket.user.image_url%>' width='30px'> <%=ticket.user.name %> (<%=ticket.user.gender %>)</li>
	<%end%>
	<%end%>
</ul>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>