config/routes.rb
Lulusum::Application.routes.draw do
  resources :matches

  resources :tickets

  resources :concerts
  
  devise_for :users, :controllers => { :registrations => "registrations" }

  

  resources :users do
    member do
      get :set_admin, :unset_admin
    end
    
    collection do
      get :love
    end
    
  end
  
  get "main_pages/home"
  get "main_pages/about"
  get "main_pages/help"
  get "main_pages/terms"

  
  root :to => "main_pages#home"
  
  match '/users/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  
  
  match '/help', to: 'main_pages#help'
  match '/about', to: 'main_pages#about'
  match '/terms', to: 'main_pages#terms'
  

  resources :test_models

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; 2012 <a href="http://Gaesin.com/">Gaesin</a>
    by Odradeck
  </small>
  <nav>
    <ul>
      <li><small><%= link_to "Term and Terms",   terms_path %></small></li>
      <li><small><%= link_to "Contact", '#' %></small></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "lulusum" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
	
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to image_tag("banner_logo_100.png", :alt => "lulusum"), root_path, id: "logo" %>
          <div class="container nav-collapse">
          	<ul class="nav pull-right">
          		<% if user_signed_in? %>
				<li><%= link_to "<div style='color:#990000;'>신청하기</div>".html_safe, concerts_path  %></li>
				<%end%>

				<!-- ><li><%= link_to "룰루섬이란?",    about_path %></li> -->
				<li class="dropdown">
                      <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">룰루섬이란? <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li><a tabindex="-1" href="about">룰루섬 이용안내</a></li>
                        <li><a tabindex="-1" href="help">룰루 QnA</a></li>
                        <li><a tabindex="-1" href="#">룰루지킴이들</a></li>
                        <li><a tabindex="-1" href="#">제휴문의</a></li>
                      </ul>
                    </li>
				<!-- <li>< link_to "Help",    help_path ></li> -->
				<% if user_signed_in? %>
  				<li><%= link_to "룰루TALK", '#' %></li>
  				<li><%= link_to "EVENT", '#' %></li>
 				<li><%= link_to(current_user.name, current_user) %></li>
 				<li><%= link_to('로그아웃', destroy_user_session_path, :method => :delete) %></li>
  					<% if current_user.admin? %>
  						<li><%= link_to "Admin", "#" %></li>
  					<% end %>
				<% else %>
  				<li> <%= link_to('로그인', new_user_session_path)  %>
  				<li><a href="/users/auth/facebook" class="services"><img src="/facebook_20.png" width="20"></a></li>
            	<!-- <li><a href="/users/auth/twitter" class="services"><img style="width:20px" src="/twitter_64.png" width="20"></a></li> -->
  				<li> <%= link_to('회원가입', new_user_registration_path)  %> </li>
  				<% end %>
  			</ul>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
      	<% flash.each do |key, value| %>
						<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
        <div class="row-fluid">
        	
        	<% if user_signed_in? %>
        	<div class="span3">
              <%= render 'shared/side'%>
             </div>
           <div class="span9"> 
           <%else%> 
           <div class="span12">
           <%end%>
           	   <%= yield %>
            </div>
            
        </div><!--/row-->
      </div><!--/content-->
		<%= render 'layouts/footer' %>
		<!--
      <footer>
        <p>&copy; Company 2012</p>
      </footer>-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>